name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build main branch
        run: |
          mkdir -p output
          cp -r index.renkon renkon-core.js loader.js index.html croquet-codemirror.js renkon-codemirror.js renkon-inspector.js assets croquet.min.js markdown-it.min.js preact.standalone.module.js output
          cp _apiKey.js output/apiKey.js

      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: output

  publish:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
